# Project
BASE_DIR = "BASE_DIR"
PROJECT_API_HOST = "PROJECT_API_HOST"

# Product information
PRODUCT_ID = "product_id"
PRODUCT_NAME = "product_name"
PRODUCT_IMAGE_NAME = "image_name"
PRODUCT_IMAGE_URL = "product_image_url"

MODELS_FOLDER = "MODELS_FOLDER"
LANGUAGE = "LANGUAGE"

# Recognition
RECOGNITION_SUCCESS_CODE = 0

# config
REDIS_URL = "REDIS_URL"
RABBITMQ_URL = "RABBITMQ_URL"
REDIS_EXPIRE_GLOBAL = "REDIS_EXPIRE_GLOBAL"

LOG_IDENT = "LOG_IDENT"
LOG_DEVICE = "LOG_DEVICE"
LOG_PROIORITY = "LOG_PROIORITY"
LOG_PATH = "LOG_PATH"

MAX_CONTENT_LENGTH = "MAX_CONTENT_LENGTH"
IMAGE_FOLDER = "IMAGE_FOLDER"
RECOGNITION_HISTORY_FOLDER = "RECOGNITION_HISTORY_FOLDER"
